/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pharmacy.mangement.system;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import connection.connection_manager;
import pharmacy.mangement.system.AdminDashboard;
/**
 *
 * @author ABO TAREK
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        user_name = new javax.swing.JTextField();
        login_btn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        role = new javax.swing.JLabel();
        user_role = new javax.swing.JComboBox<>();
        password = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pharmacy-management-system");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Login");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 190, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Passward");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, -1, -1));

        user_name.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        user_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_nameActionPerformed(evt);
            }
        });
        jPanel1.add(user_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 330, 308, 30));

        login_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        login_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        login_btn.setText("Login");
        login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_btnActionPerformed(evt);
            }
        });
        jPanel1.add(login_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 460, -1, -1));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 400, -1, -1));

        role.setBackground(new java.awt.Color(255, 255, 255));
        role.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        role.setForeground(new java.awt.Color(255, 255, 255));
        role.setText("Role");
        jPanel1.add(role, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 90, 30));

        user_role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Pharmacist" }));
        jPanel1.add(user_role, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 270, 310, 30));
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 390, 308, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pharmacy Management System (10).png"))); // NOI18N
        jLabel5.setToolTipText("");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, -10, 1390, 760));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_btnActionPerformed
        // إنشاء كائن لإدارة الاتصال
    connection_manager connect = new connection_manager();
    // التحقق من أن الحقول ليست فارغة
    String role = user_role.getSelectedItem().toString();
    String username = user_name.getText().strip();
    String pass = password.getText();
    if (username.isEmpty() || pass.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Username or password cannot be empty");
        return;
    }

    // التحقق من اسم المستخدم وكلمة المرور
    boolean isValid = connect.CheckCorrectPassword(role, "user_name", "password", username, pass);

    if (isValid) {    
        setVisible(false);
        // إذا كان التحقق ناجحًا
        if(role.equals("Admin")){
            String[] userInfo = connect.getRow("admin", "user_name", username);
            String name = userInfo[2];
            String email = userInfo[3];
            String phone = userInfo[4];
            String sallary = userInfo[7];
            String User_Name = userInfo[5];
            String password_ = userInfo[6];
            String id = userInfo[0];
            AdminDashboard adminDashboard = new AdminDashboard(id,User_Name,name,phone,email,password_,sallary,role);
            adminDashboard.setVisible(true); 
        }else if (role.equals("Pharmacist")) {
            String[] userInfo = connect.getRow("pharmacist", "user_name", username);
            String name = userInfo[2];
            String email = userInfo[3];
            String phone = userInfo[4];
            String sallary = userInfo[5];
            String User_Name = userInfo[6];
            String password_ = userInfo[7];
            String id = userInfo[0];
            PharmacistDashboard pharma;
            pharma = new PharmacistDashboard(id,User_Name,name,phone,email,password_,sallary,role);
            pharma.setVisible(true);
        }
    } else {
        // إذا كان التحقق فاشلًا
        JOptionPane.showMessageDialog(null, "Wrong username or password");
    }
    }//GEN-LAST:event_login_btnActionPerformed

    private void user_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_nameActionPerformed

    }//GEN-LAST:event_user_nameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login login = new Login();
                login.setVisible(true); 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login_btn;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel role;
    private javax.swing.JTextField user_name;
    private javax.swing.JComboBox<String> user_role;
    // End of variables declaration//GEN-END:variables
}
